import { useState } from "react";
import { Copy, Check, Shuffle, Download } from "lucide-react";
import { caesarShift, toNumber, toMorse, toBinary, toSymbol } from "../utils/ciphers";
import { showToast } from "../utils/toast";

const MESSAGE_POOL = [
  "THE TREASURE IS BURIED UNDER THE OAK TREE",
  "MEET ME AT MIDNIGHT BY THE OLD BRIDGE",
  "THE EAGLE HAS LANDED",
  "OPERATION SUNRISE IS CONFIRMED",
  "AVOID THE NORTH CORRIDOR",
  "THE PACKAGE HAS BEEN DELIVERED SAFELY",
  "DO NOT TRUST THE MESSENGER",
  "RENDEZVOUS AT DAWN AT SECTOR SEVEN",
  "THE CODE IS HIDDEN IN THE LIBRARY",
  "ALL AGENTS REPORT TO HEADQUARTERS",
  "THE MISSION IS COMPLETE RETURN TO BASE",
  "DANGER APPROACHING FROM THE EAST",
  "ACTIVATE PROTOCOL ALPHA NOW",
  "THE SECRET IS SAFE WITH US",
  "ENEMIES HAVE BROKEN THE OUTER PERIMETER",
  "CHANGE YOUR FREQUENCIES IMMEDIATELY",
  "MAINTAIN RADIO SILENCE UNTIL FURTHER NOTICE",
  "THE MOLE HAS BEEN IDENTIFIED",
  "DESTROY THIS MESSAGE AFTER READING",
  "YOU ARE NOW A CERTIFIED SPY",
];

type CipherType = "caesar" | "caesar13" | "number" | "morse" | "reverse" | "binary" | "symbol";

const CIPHER_OPTIONS: { id: CipherType; label: string; emoji: string; color: string }[] = [
  { id: "caesar",   label: "Caesar (Shift 3)",  emoji: "🔄", color: "from-purple-500 to-indigo-600" },
  { id: "caesar13", label: "ROT13 (Shift 13)",  emoji: "🔁", color: "from-violet-500 to-purple-700" },
  { id: "number",   label: "Number Cipher",     emoji: "🔢", color: "from-blue-500 to-cyan-600" },
  { id: "morse",    label: "Morse Code",        emoji: "📡", color: "from-green-500 to-teal-600" },
  { id: "reverse",  label: "Reverse Cipher",    emoji: "↩️", color: "from-orange-500 to-red-500" },
  { id: "binary",   label: "Binary Code",       emoji: "💾", color: "from-pink-500 to-rose-600" },
  { id: "symbol",   label: "Symbol Cipher",     emoji: "🔣", color: "from-yellow-500 to-amber-600" },
];

function encode(text: string, cipher: CipherType): string {
  switch (cipher) {
    case "caesar":   return caesarShift(text, 3);
    case "caesar13": return caesarShift(text, 13);
    case "number":   return toNumber(text);
    case "morse":    return toMorse(text);
    case "reverse":  return text.split("").reverse().join("");
    case "binary":   return toBinary(text);
    case "symbol":   return toSymbol(text);
  }
}

function getKeyInfo(cipher: CipherType): string {
  switch (cipher) {
    case "caesar":   return "Shift each letter back by 3 to decode";
    case "caesar13": return "Apply ROT13 again to decode (it's its own inverse!)";
    case "number":   return "Replace each number with its letter (1=A, 2=B, ...)";
    case "morse":    return "Use a Morse Code chart to decode";
    case "reverse":  return "Reverse the entire message";
    case "binary":   return "Convert each 8-bit group to a number, then to a letter";
    case "symbol":   return "Use the symbol key: ! → A, @ → B, # → C...";
  }
}

export default function RandomMessageGen() {
  const [cipher, setCipher] = useState<CipherType>("caesar");
  const [plain, setPlain] = useState("");
  const [encrypted, setEncrypted] = useState("");
  const [copied, setCopied] = useState(false);
  const [customMode, setCustomMode] = useState(false);
  const [customText, setCustomText] = useState("");

  const generate = () => {
    const msg = MESSAGE_POOL[Math.floor(Math.random() * MESSAGE_POOL.length)];
    setPlain(msg);
    setEncrypted(encode(msg, cipher));
    setCopied(false);
  };

  const generateCustom = () => {
    const text = customText.trim().toUpperCase();
    if (!text) { showToast("Enter a message first!", "error"); return; }
    setPlain(text);
    setEncrypted(encode(text, cipher));
    setCopied(false);
  };

  const copy = () => {
    if (!encrypted) return;
    navigator.clipboard.writeText(encrypted);
    setCopied(true);
    showToast("Copied to clipboard!", "success");
    setTimeout(() => setCopied(false), 2000);
  };

  const download = () => {
    if (!encrypted) return;
    const content = `SECRET MESSAGE\n${"=".repeat(40)}\nOriginal: ${plain}\nCipher: ${CIPHER_OPTIONS.find(c => c.id === cipher)?.label}\nEncrypted: ${encrypted}\nDecoding Key: ${getKeyInfo(cipher)}\n${"=".repeat(40)}\nGenerated by Mystery Messaging Machine`;
    const blob = new Blob([content], { type: "text/plain" });
    const a = Object.assign(document.createElement("a"), { href: URL.createObjectURL(blob), download: "secret-message.txt" });
    a.click();
    showToast("Secret message downloaded!", "info");
  };

  const activeCipher = CIPHER_OPTIONS.find((c) => c.id === cipher)!;

  return (
    <section id="message-gen" className="py-20 px-4 bg-background">
      <div className="max-w-4xl mx-auto">
        <div className="text-center mb-10">
          <span className="inline-block bg-teal-100 dark:bg-teal-900/40 text-teal-700 dark:text-teal-300 text-sm font-bold px-4 py-1.5 rounded-full mb-4">
            📨 Tool
          </span>
          <h2 className="text-4xl sm:text-5xl font-black mb-4">
            Secret Message <span className="gradient-text">Generator</span>
          </h2>
          <p className="text-muted-foreground text-lg max-w-xl mx-auto">
            Generate a random spy message and encrypt it with any cipher — then share it with a friend to decode!
          </p>
        </div>

        <div className="bg-card border border-border rounded-3xl p-6 sm:p-8 shadow-sm">
          <div className="mb-6">
            <div className="text-sm font-bold mb-3">1. Choose a cipher:</div>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
              {CIPHER_OPTIONS.map((c) => (
                <button key={c.id} onClick={() => { setCipher(c.id); setEncrypted(""); setPlain(""); }}
                  className={`flex items-center gap-2 rounded-xl px-3 py-2.5 text-xs font-bold border-2 transition-all ${
                    cipher === c.id
                      ? `bg-gradient-to-r ${c.color} text-white border-transparent shadow-md`
                      : "border-border bg-muted text-muted-foreground hover:bg-muted/70"
                  }`}>
                  <span>{c.emoji}</span> {c.label}
                </button>
              ))}
            </div>
          </div>

          <div className="mb-6">
            <div className="text-sm font-bold mb-3">2. Choose message source:</div>
            <div className="flex gap-2 mb-3">
              <button onClick={() => setCustomMode(false)}
                className={`flex-1 py-2 rounded-xl text-sm font-bold border-2 transition-all ${!customMode ? "border-primary bg-primary/10 text-primary" : "border-border bg-muted text-muted-foreground"}`}>
                🎲 Random Spy Message
              </button>
              <button onClick={() => setCustomMode(true)}
                className={`flex-1 py-2 rounded-xl text-sm font-bold border-2 transition-all ${customMode ? "border-primary bg-primary/10 text-primary" : "border-border bg-muted text-muted-foreground"}`}>
                ✏️ Write My Own
              </button>
            </div>

            {customMode ? (
              <div className="flex gap-2">
                <input value={customText} onChange={(e) => setCustomText(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && generateCustom()}
                  placeholder="Type your secret message…"
                  className="flex-1 bg-muted border border-border rounded-xl px-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-primary"
                />
                <button onClick={generateCustom}
                  className="gradient-bg text-white font-bold px-4 py-2.5 rounded-xl hover:opacity-90 transition-all text-sm">
                  Encrypt
                </button>
              </div>
            ) : (
              <button onClick={generate}
                className="w-full gradient-bg text-white font-black py-4 rounded-2xl hover:opacity-90 transition-all hover:scale-[1.01] active:scale-[0.99] flex items-center justify-center gap-2 text-lg">
                <Shuffle className="w-5 h-5" /> Generate Random Message
              </button>
            )}
          </div>

          {encrypted && (
            <div className="animate-fade-in">
              <div className={`bg-gradient-to-br ${activeCipher.color} rounded-2xl p-5 text-white mb-4`}>
                <div className="text-xs font-bold opacity-70 uppercase tracking-wide mb-1">
                  {activeCipher.emoji} {activeCipher.label} — Encrypted:
                </div>
                <div className="font-mono text-sm sm:text-base font-bold break-all leading-relaxed">
                  {encrypted}
                </div>
              </div>

              <div className="bg-muted rounded-2xl p-4 mb-4">
                <div className="text-xs font-bold text-muted-foreground uppercase tracking-wide mb-1">Original Message</div>
                <div className="font-mono text-sm font-semibold">{plain}</div>
              </div>

              <div className="bg-blue-50 dark:bg-blue-950/40 border border-blue-200 dark:border-blue-800 rounded-2xl p-4 mb-4">
                <div className="text-xs font-bold text-blue-700 dark:text-blue-300 uppercase tracking-wide mb-1">🔑 Decoding Key</div>
                <div className="text-sm text-foreground">{getKeyInfo(cipher)}</div>
              </div>

              <div className="flex gap-2">
                <button onClick={copy}
                  className="flex-1 flex items-center justify-center gap-2 bg-muted hover:bg-muted/70 font-bold px-4 py-3 rounded-xl transition-all text-sm">
                  {copied ? <Check className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />}
                  {copied ? "Copied!" : "Copy Encrypted Text"}
                </button>
                <button onClick={download}
                  className="flex-1 flex items-center justify-center gap-2 bg-muted hover:bg-muted/70 font-bold px-4 py-3 rounded-xl transition-all text-sm">
                  <Download className="w-4 h-4" /> Download .txt
                </button>
              </div>
            </div>
          )}
        </div>

        <div className="mt-5 bg-amber-50 dark:bg-amber-950/30 border border-amber-200 dark:border-amber-800 rounded-2xl p-4">
          <div className="font-bold text-amber-700 dark:text-amber-300 text-sm mb-1">💡 Challenge a Friend!</div>
          <p className="text-sm text-foreground">Generate a secret message, encrypt it, and copy it to a friend. See if they can decode it! Tell them which cipher you used as a hint.</p>
        </div>
      </div>
    </section>
  );
}
